---
- name: Add/verify Plex apt repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: Add/verify Plex GPG key to apt
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Install latest public release of Plex
  apt:
    name: plexmediaserver
    state: latest
    update_cache: yes
  register: update_response
...